ensure_packages expects an array
Using the following code

network::bridge::static { 'br0':
  ensure    => 'up',
  ipaddress => '10.101.0.0',
  netmask   => '255.255.0.0',
}

results in the following error

Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, ensure_packages(): Requires array given (String) at /home/centos/openshift/modules/network/manifests/bridge/static.pp:85:3  at /home/centos/openshift/manifests/site.pp:10 on node openshift-node-2.localdomain